---
name: Lint
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    tags:
      - v*.*.*
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup python version
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: >
          python -m pip install --upgrade pip

          pip install flake8 pytest

          if [ –f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
      - name: black formatting
        uses: psf/black@stable
        with:
          options: --check --verbose
          src: ./src
      - name: lint with flake8
        run: >
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
